import React, { useState } from "react";

type Stage = "idle" | "awaiting" | "approved" | "executed";

export default function App(): JSX.Element {
  const [ai1, setAi1] = useState(false);
    const [ai2, setAi2] = useState(false);
      const [stage, setStage] = useState<Stage>("idle");
        const [note, setNote] = useState("");
          const [log, setLog] = useState<string[]>([]);

            const startValidation = () => {
                setAi1(false);
                    setAi2(false);
                        setStage("awaiting");
                            pushLog("Validation started");
                              };

                                const approve = (which: 1 | 2) => {
                                    if (stage !== "awaiting") return;
                                        if (which === 1 && !ai1) {
                                              setAi1(true);
                                                    pushLog("AI-1 approved");
                                                        }
                                                            if (which === 2 && !ai2) {
                                                                  setAi2(true);
                                                                        pushLog("AI-2 approved");
                                                                            }
                                                                                // If both approved, move to approved stage
                                                                                    setTimeout(() => {
                                                                                          if ((which === 1 && ai2) || (which === 2 && ai1) || (ai1 && ai2)) {
                                                                                                  setStage("approved");
                                                                                                          pushLog("Both AIs approved");
                                                                                                                }
                                                                                                                    }, 0);
                                                                                                                      };

                                                                                                                        const execute = () => {
                                                                                                                            if (stage !== "approved") {
                                                                                                                                  alert("Both AIs must approve before execution.");
                                                                                                                                        return;
                                                                                                                                            }
                                                                                                                                                setStage("executed");
                                                                                                                                                    pushLog(`Executed${note ? ` — note: ${note}` : ""}`);
                                                                                                                                                      };

                                                                                                                                                        const resetAll = () => {
                                                                                                                                                            setAi1(false);
                                                                                                                                                                setAi2(false);
                                                                                                                                                                    setStage("idle");
                                                                                                                                                                        setNote("");
                                                                                                                                                                            pushLog("Reset to idle");
                                                                                                                                                                              };

                                                                                                                                                                                const pushLog = (entry: string) => {
                                                                                                                                                                                    const time = new Date().toLocaleTimeString();
                                                                                                                                                                                        setLog((l) => [`[${time}] ${entry}`, ...l].slice(0, 20));
                                                                                                                                                                                          };

                                                                                                                                                                                            return (
                                                                                                                                                                                                <div style={{ fontFamily: "Inter, Arial, sans-serif", padding: 20, maxWidth: 720 }}>
                                                                                                                                                                                                      <h2>Validation Playground</h2>

                                                                                                                                                                                                            <div style={{ marginBottom: 12 }}>
                                                                                                                                                                                                                    <strong>Stage:</strong>{" "}
                                                                                                                                                                                                                            <span style={{ textTransform: "capitalize", marginLeft: 8 }}>{stage}</span>
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                        <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 12 }}>
                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                          onClick={startValidation}
                                                                                                                                                                                                                                                                    disabled={stage === "awaiting"}
                                                                                                                                                                                                                                                                              style={{ padding: "8px 12px" }}
                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                Start Validation
                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                          onClick={() => approve(1)}
                                                                                                                                                                                                                                                                                                                                    disabled={ai1 || stage !== "awaiting"}
                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                          padding: "8px 12px",
                                                                                                                                                                                                                                                                                                                                                                      background: ai1 ? "#e6ffed" : undefined,
                                                                                                                                                                                                                                                                                                                                                                                  border: ai1 ? "1px solid #2ecc71" : undefined,
                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                              {ai1 ? "AI-1 ✅" : "AI-1 Approve"}
                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => approve(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={ai2 || stage !== "awaiting"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "8px 12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: ai2 ? "#e6ffed" : undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: ai2 ? "1px solid #2ecc71" : undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {ai2 ? "AI-2 ✅" : "AI-2 Approve"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={execute}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={stage !== "approved"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ padding: "8px 12px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Execute
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={resetAll} style={{ padding: "8px 12px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Reset
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ marginBottom: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label style={{ display: "block", marginBottom: 6 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>Execution note (optional)</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={note}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setNote(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Add a short note to record with execution"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ width: "100%", padding: 8, boxSizing: "border-box" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginBottom: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong>Approvals:</strong>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ marginLeft: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  AI-1: {ai1 ? "✅" : "❌"}; AI-2: {ai2 ? "✅" : "❌"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: 18 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h4 style={{ marginBottom: 8 }}>Activity log</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid #eee",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                maxHeight: 220,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            overflow: "auto",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: "#fafafa",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {log.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ color: "#666" }}>No activity yet.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ul style={{ margin: 0, paddingLeft: 18 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {log.map((l, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li key={i} style={{ marginBottom: 6, fontSize: 13 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {l}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }